project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "SGMT 431"

  navbar:
    background: "#03a9e6"
    foreground: light
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: Lecture 1
        menu:
          - href: lecture-1/index.html
            text: Tutorials
          - href: lecture-1/slides/lecture-1-slides.html
            text: Slides

  search:
    location: navbar
    type: textbox

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    html-math-method: mathml
    grid:
      sidebar-width: 240px
      body-width: 760px
      margin-width: 220px
      gutter-width: 2rem